[package]
name = "pipe-dream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
s-macro = "0.1"
iced = "0.7"
iced_wgpu = "0.8"
iced_graphics = "0.6"
thiserror = "1.0"
nu-protocol = "0.75"
nu-engine = "0.75"
nu-parser = "0.75"
nu-command = "0.75"
dirs = "4.0"
once_cell = "1.17"